config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'
  get 'homeauth/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

  resources :groups
  resources :entities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/entity.rb
class Entity < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities, foreign_key: 'entity_id'
  has_many :groups, through: :group_entities

  validates :name, presence: true, length: { minimum: 3 }
  validates :amount, presence: true
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: %i[show edit update destroy]

  # GET /entities or /entities.json
  def index
    @entities = Entity.where(author_id: current_user.id)
    
  end

  # GET /entities/1 or /entities/1.json
  def show; end

  # GET /entities/new
  def new
    @entity = Entity.new
  end

  # GET /entities/1/edit
  def edit; end

  # POST /entities or /entities.json
  def create
    @entity = Entity.new(name: entity_params[:name], author_id: current_user.id, amount: entity_params[:amount].to_f)
    respond_to do |format|
      if entity_params[:groups].any? && @entity.save
        entity_params[:groups].each do |group_id|
          unless Group.exists?(group_id)
            format.html { render :new, status: "Group #{group_id} does not exist" }
            format.json { render json: "Group #{group_id} does not exist", status: "Group #{group_id} does not exist" }
          end
          @entity.groups << Group.find(group_id)
        end
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully created.' }
        format.json { render :show, status: :created, location: @entity }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entities/1 or /entities/1.json
  def update
    respond_to do |format|
      if @entity.update(entity_params)
        format.html { redirect_to entity_url(@entity), notice: 'Entity was successfully updated.' }
        format.json { render :show, status: :ok, location: @entity }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entities/1 or /entities/1.json
  def destroy
    @entity.destroy

    respond_to do |format|
      format.html { redirect_to entities_url, notice: 'Entity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entity
    @entity = Entity.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entity_params
    params.require(:entity).permit!
  end
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_entity.html.erb
<div id="<%= dom_id entity %>" class="card d-flex flex-col col-12 m-auto mb-2 shadow">
  <div class="card-header">
    <h3 class="card-text">
      <%= link_to entity.name.capitalize, entity, class: "text-muted" %>
    </h3>
  </div>
  <div class="card-body">
    <p class="card-text">
      Date: <%= entity.created_at.strftime("%d/%h/%Y %I:%M %p") %>
    </p>
    <p class="card-text">
      Amount: 
      <strong>$<%= entity.amount %></strong>
    </p>
  </div>
  <div class="card-footer">
    <p class="card-text">
      Groups:
      <% entity.groups.each do |group| %>
        <%= link_to group.name, group, class: "text-muted" %>
      <% end %>
    </p>
  </div>
</div>

app/views/entities/_form.html.erb
<%= form_with(model: entity) do |form| %>
  <% if entity.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(entity.errors.count, "error") %> prohibited this entity from being saved:</h2>

      <ul>
        <% entity.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="form-group">
    <%= form.label :amount %>
    <%= form.number_field :amount, step: 0.5 %>
  </div>

  <div class="card">
    <p class="card-header">Categories</p>
    <% Group.where(author_id: current_user.id).each do |group| %>
      <div>
        <%= form.check_box :groups, {multiple: true}, group.id, nil %>
        <%= group.name %>
      </div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/entities/_navbar.html.erb
<div class="d-flex flex-row justify-content-between align-items-center bg-primary fixed-top text-light p-1", style="height: 50px;">
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    <i class="fa-solid fa-bars"></i>
  </a>
  <div>TRANSACTIONS</div>
  <div class="actions">
    <%= button_to "Home", entities_path, method: :get, class: "bg-transparent border-0 text-light" %>
  </div>
</div>
<%= render "shared/sidebar" %>
<br><br><br>

app/views/entities/edit.html.erb
<%= render "navbar" %>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Show this entity", @entity %> |
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/index.html.erb
<%= render "navbar" %>
<div class="card">
  <h2 class="card-header">Transactions Data:</h2>
  <div class="card-body">
    <p>Total amount: $<%= @entities.sum(:amount) %> </p>
    <p>Total of transactions: <%= @entities.count %> </p>
    <p>Average amount: $<%= @entities.average(:amount) %> </p>
    <p>Maximum amount: $<%= @entities.maximum(:amount) %> </p>
    <p>Minimum amount: $<%= @entities.minimum(:amount) %> </p>
  </div>
</div>
<%= link_to "+ TRANSACTION", new_entity_path %>
<h2>List: </h2>

<div id="entities">
  <% @entities.each do |entity| %>
    <%= render entity %>
  <% end %>
</div>

app/views/entities/new.html.erb
<%= render "navbar" %>

<%= render "form", entity: @entity %>

<br>

<div>
  <%= link_to "Back to entities", entities_path %>
</div>

app/views/entities/show.html.erb
<%= render "navbar" %>

<%= render @entity %>

<div>
  <!-- <%= link_to "Edit this entity", edit_entity_path(@entity) %> | -->
  <%= link_to "Back to entities", entities_path %><hr/>

  <%= button_to "Destroy this entity", @entity, method: :delete, class: "btn btn-danger col-12" %>
</div>