config/routes.rb
Rails.application.routes.draw do
  get 'transactions/index'
  get 'homeauth/index'
  devise_for :users, controllers: { sessions: 'users/sessions', registrations: 'users/registrations' }

  authenticated :user do
    root 'groups#index', as: :authenticated_root
  end

  unauthenticated do
    root 'home#index', as: :unauthenticated_root
  end

  resources :groups
  resources :entities
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :author, class_name: 'User'
  has_many :group_entities, foreign_key: 'group_id'
  has_many :entities, through: :group_entities
  has_one_attached :icon

  validates :name, presence: true, length: { minimum: 3 }
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  # GET /groups or /groups.json
  def index
    @groups = Group.includes(:entities).where(author_id: current_user.id)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    @group = Group.new(group_params)
    @group.author_id = current_user.id

    respond_to do |format|
      if @group.save
        format.html { redirect_to group_url(@group), notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <% if group.icon.attached? %>
      <%= image_tag group.icon, style: "width: 200px; display: block" %>
    <% end %>

    <%= form.label :icon %>
    <%= form.file_field :icon, class: "form-control" %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div id="<%= dom_id group %>" class="card d-flex flex-row col-12 m-auto mb-2 shadow">
  <% if group.icon.attached? %>
    <%= image_tag group.icon, class: "ard-img-left border m-1", style: "height: 7em; width: 7em;" %>
  <% else %>
    <img class="card-img-left border m-1" style="height: 7em; width: 7em;" src="https://us.123rf.com/450wm/pavelstasevich/pavelstasevich1811/pavelstasevich181101032/112815935-no-image-available-icon-flat-vector-illustration.jpg?ver=6" alt="Card image cap">
  <% end %>
  
  <div class="card-body col-5">
    <p class="card-text">
      <%= link_to group.name, group, class: "text-muted" %>
    </p>
  </div>
  <div class="card-body col-3">
    <p class="card-text">
      <strong>$<%= group.entities.sum(:amount) %></strong>
    </p>
  </div>
</div>

app/views/groups/_navbar.html.erb
<div class="d-flex flex-row justify-content-between align-items-center bg-primary fixed-top text-light p-1", style="height: 50px;">
  <a class="btn btn-primary" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
    <i class="fa-solid fa-bars"></i>
  </a>
  <div>CATEGORIES</div>
  <div class="actions">
    <%= button_to "Log in", homeauth_index_path, method: :get, class: "bg-transparent border-0 text-light" %>
  </div>
</div>
<%= render "shared/sidebar" %>
<br><br><br>

app/views/groups/edit.html.erb
<%= render "navbar" %>
<h1>Editing Category</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<%= render "navbar" %>

<%= link_to "+ Category", new_group_path %>
<div id="groups">
  <% @groups.each do |group| %>
    <%= render group %>
  <% end %>
</div>

app/views/groups/new.html.erb
<%= render "navbar" %>
<h1>New Category</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/show.html.erb
<%= render "navbar" %>
<p style="color: green"><%= notice %></p>

<%= render @group %>

<div>
  <%= link_to "Edit this group", edit_group_path(@group) %> |
  <%= link_to "Back to groups", groups_path %>
  <hr/>

  <%= button_to "Destroy this group", @group, method: :delete, class: "btn btn-danger col-12" %>
</div>
<hr>
<h2>Transactions in this category</h2>
<div id="entities">
  <% @group.entities.each do |entity| %>
    <%= render 'entities/entity', entity: entity %>
  <% end %>
</div>